name: Build Flet APK and AAB

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet
        # CORRIGIDO: Agora aponta para o requirements.txt dentro da pasta app
        if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17' # Necessário para o compilador do Android (Gradle) rodar sem erros

    - name: Build APK with Flet
      run: |
        # O comando 'yes' injeta a resposta "y" automaticamente para aceitar o download do Flutter SDK
        yes | flet build apk app

    - name: Build AAB (App Bundle) with Flet
      run: |
        # Gerando o formato obrigatório para a Play Store
        yes | flet build appbundle app

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: meu-jardim-apk
        path: build/apk/app-release.apk
        
        #Variables do python
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: meu-jardim-apk
        path: app/build/apk/*.apk # <- CORRIGIDO: Adicionado 'app/' no início do caminho

    - name: Upload AAB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: meu-jardim-aab
        path: app/build/appbundle/*.aab # # Captura o arquivo .aab gerado